server:
  port: 32009
  ssl:
      serverCrt: /home/krt/iot/iot-mqttsev-32009/cert/server.crt
      serverKey: /home/krt/iot/iot-mqttsev-32009/cert/pkcs8_server.key
      caCrt: /home/krt/iot/iot-mqttsev-32009/cert/ca.crt
      password: 123456

spring:
  datasource:
    username: root
    password: krt83567922
    url: jdbc:mysql://172.0.52.112:3306/iot-mqtt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver