server:
  port: 32009
  ssl:
    serverCrt: E:\workspace-iot\IOT_MQTT\src\main\resources\cert\server.crt
    serverKey: E:\workspace-iot\IOT_MQTT\src\main\resources\cert\pkcs8_server.key
    caCrt: E:\workspace-iot\IOT_MQTT\src\main\resources\cert\ca.crt
    password: 123456

spring:
  datasource:
    username: root
    password: krt83567922
    url: jdbc:mysql://172.0.52.112:3306/iot-mqtt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver