server:
  port: 8088

spring:
  datasource:
    username: root
    password: krt83567922
    url: jdbc:mysql://localhost:3306/netty_mqtt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.krt.mqtt.server.entity