server:
  port: 32001
  jks:
    path: E:\workspace-iot\IOT_MQTT\src\main\resources\cert\SHA256withRSA_iot.krtyun.com.jks
    password: az8TMPQ78S1f

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/netty_mqtt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver