server:
  port: 32001
  jks:
    path: E:\workspace-iot\IOT_MQTT\src\main\resources\cert\SHA256withRSA_iot.krtyun.com.jks
    password: az8TMPQ78S1f

spring:
  datasource:
    username: root
    password: krt83567922
    url: jdbc:mysql://172.0.52.112:3306/iot-cloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver