/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __IRDecode__
#define __IRDecode__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jint JNICALL Java_com_krt_mqtt_server_ir_core_IRDecode_irOpen (JNIEnv *env, jobject, jint, jint, jstring);
JNIEXPORT jintArray JNICALL Java_com_krt_mqtt_server_ir_core_IRDecode_irDecode (JNIEnv *env, jclass, jint, jobject, jint);
JNIEXPORT jobject JNICALL Java_com_krt_mqtt_server_ir_core_IRDecode_mqttEncode (JNIEnv *env, jobject, jintArray);

#ifdef __cplusplus
}
#endif

#endif /* __IRDecode__ */
